local E, L, V, P, G = unpack(ElvUI);
local PrioUI = E:GetModule('PrioUI');

if not _G["Afflicted"] then return; end

function PrioUI:SetupAfflicted()

	Afflicted.db.profile.anchors = {
		["defenses"] = {
			["enabled"] = false,
			["position"] = {
				["y"] = 675.377880937194,
				["x"] = 253.689068642925,
			},
			["display"] = "icons",
		},
		["interrupts"] = {
			["position"] = {
				["y"] = 420.577961572926,
				["x"] = 582.245283195935,
			},
			["display"] = "icons",
		},
		["cooldowns"] = {
			["announce"] = true,
			["announceDest"] = "rwframe",
			["position"] = {
				["y"] = 420.555565739051,
				["x"] = 767.999671374419,
			},
			["display"] = "icons",
			["icon"] = "RIGHT",
		},
		["buffs"] = {
			["enabled"] = false,
			["position"] = {
				["y"] = 671.666552722327,
				["x"] = 361.866393310984,
			},
			["display"] = "icons",
		},
		["spells"] = {
			["enabled"] = false,
			["position"] = {
				["y"] = 678.399886218704,
				["x"] = 316.778610101155,
			},
			["display"] = "icons",
		},
		["damage"] = {
			["enabled"] = false,
			["position"] = {
				["y"] = 674.622151752228,
				["x"] = 412.999749583869,
			},
			["display"] = "icons",
		},
	}
	Afflicted.db.profile.spells = {
		[19647] = "{cooldown=24;cdAnchor='interrupts';class='WARLOCK';}",
		[108294] = "{type='buff';duration=45;anchor='damage';cooldown=360;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[118000] = "{cdDisabled=true;class='WARRIOR';cooldown=60;cdAnchor='cooldowns';}",
		[53271] = "{duration=4;anchor='buffs';cooldown=45;cdAnchor='cooldowns';class='HUNTER';}",
		[66] = "{disabled=true;duration=23;anchor='defenses';cooldown=300;cdDisabled=true;cdAnchor='cooldowns';class='MAGE';}",
		[51271] = "{disabled=true;anchor='damage';disabled=true;duration=20;cooldown=60;cdDisabled=true;cdAnchor='cooldowns';class='DEATHKNIGHT';}",
		[132469] = "{cooldown=30;cdAnchor='cooldowns';class='DRUID';}",
		[46968] = "{cdDisabled=false;class='WARRIOR';cooldown=20;cdAnchor='cooldowns';}",
		[33206] = "{type='buff';disabled=true;class='PRIEST';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=180;duration=8;}",
		[48020] = "{cdDisabled=true;class='WARLOCK';cooldown=30;cdAnchor='spells';}",
		[105809] = "{type='buff';duration=18;anchor='damage';cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='PALADIN';}",
		[1044] = "{type='buff';disabled=true;class='PALADIN';cdAnchor='cooldowns';cdDisabled=true;anchor='spells';cooldown=25;duration=6;}",
		[61336] = "{type='buff';disabled=true;class='DRUID';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=180;duration=12;}",
		[82939] = "{cooldown=24;cdAnchor='interrupts';class='HUNTER';}",
		[108200] = "{disabled=true;anchor='defenses';disabled=true;duration=8;cooldown=60;cdDisabled=true;cdAnchor='cooldowns';class='DEATHKNIGHT';}",
		[96231] = "{cooldown=15;cdAnchor='interrupts';class='PALADIN';}",
		[122783] = "{type='buff';disabled=true;duration=6;anchor='defenses';cooldown=90;cdAnchor='cooldowns';class='MONK';}",
		[20066] = "{disabled=true;cdDisabled=true;class='PALADIN';cooldown=15;cdAnchor='cooldowns';}",
		[132409] = "{cooldown=24;cdAnchor='interrupts';class='WARLOCK';}",
		[2983] = "{type='buff';disabled=true;class='ROGUE';cdAnchor='cooldowns';cdDisabled=true;anchor='buffs';cooldown=60;duration=15;}",
		[171138] = "{cooldown=24;cdAnchor='interrupts';class='WARLOCK';}",
		[36554] = "{duration=2;disabled=true;cdDisabled=true;anchor='buffs';class='ROGUE';cooldown=20;cdAnchor='cooldowns';}",
		[2094] = "{disabled=false;class='ROGUE';cooldown=120;cdAnchor='cooldowns';}",
		[7744] = "{cooldown=180;cdAnchor='defenses'}",
		[14185] = "{cooldown=300;cdDisabled=true;cdAnchor='cooldowns';resets={1856,2983,5277};class='ROGUE'}",
		[31884] = "{type='buff';disabled=true;class='PALADIN';cdAnchor='cooldowns';cdDisabled=false;anchor='damage';cooldown=120;duration=20;}",
		[1499] = "{type='trap';duration=60;cdAnchor='cooldowns';cdDisabled=false;anchor='spells';disabled=true;cooldown=15;class='HUNTER';}",
		[119996] = "{disabled=true;cdDisabled=true;class='MONK';cooldown=25;cdAnchor='cooldowns';}",
		[42292] = "{cdDisabled=true;cooldown=120;cdAnchor='defenses';}",
		[5211] = "{disabled=true;cdDisabled=false;class='DRUID';cooldown=50;cdAnchor='interrupts';}",
		[48707] = "{cdDisabled=true;type='buff';disabled=true;duration=5;cooldown=45;anchor='defenses';cdAnchor='cooldowns';class='DEATHKNIGHT';}",
		[108920] = "{cooldown=45;cdAnchor='cooldowns';class='PRIEST';}",
		[102051] = "{cdDisabled=true;class='MAGE';cooldown=20;cdAnchor='spells';}",
		[99] = "{cooldown=30;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[59752] = "{cooldown=120;cdAnchor='defenses'}",
		[165341] = "{type='buff';duration=15;anchor='buffs';cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='SHAMAN';}",
		[47528] = "{cooldown=15;cdAnchor='interrupts';class='DEATHKNIGHT';}",
		[49576] = "{cdDisabled=true;class='DEATHKNIGHT';cooldown=20;cdAnchor='spells';}",
		[64382] = "{cooldown=300;cdDisabled=true;cdAnchor='cooldowns';class='WARRIOR';}",
		[11958] = "{cooldown=180;cdDisabled=true;cdAnchor='cooldowns';resets={44572,45438};class='MAGE'}",
		[12472] = "{type='buff';disabled=true;class='MAGE';cdAnchor='cooldowns';cdDisabled=false;anchor='damage';cooldown=180;duration=20;}",
		[44572] = "{cooldown=30;cdAnchor='spells';class='MAGE';}",
		[20589] = "{cdDisabled=true;cooldown=105;cdAnchor='defenses';}",
		[30283] = "{cooldown=30;cdAnchor='cooldowns';class='WARLOCK';}",
		[31821] = "{type='buff';disabled=true;duration=6;anchor='defenses';class='PALADIN';cooldown=180;cdAnchor='cooldowns';}",
		[23920] = "{type='buff';disabled=true;duration=5;cdDisabled=true;cooldown=20;cdAnchor='cooldowns';class='WARRIOR';}",
		[47481] = "{cooldown=60;cdDisabled=true;cdAnchor='spells';class='DEATHKNIGHT';}",
		[96268] = "{class='DEATHKNIGHT';disabled=true;cdDisabled=true;anchor='buff';duration=6;cooldown=30;cdAnchor='cooldowns';}",
		[113656] = "{cooldown=25;cdAnchor='spells';class='MONK';}",
		[50334] = "{class='DRUID';type='buff';disabled=true;cdDisabled=true;anchor='damage';duration=15;cooldown=180;cdAnchor='cooldowns';}",
		[6789] = "{cooldown=45;cdAnchor='cooldowns';class='WARLOCK';}",
		[19386] = "{cooldown=45;cdAnchor='cooldowns';class='HUNTER';}",
		[116844] = "{disabled=true;duration=8;anchor='spells';class='MONK';cooldown=45;cdAnchor='cooldowns';}",
		[122470] = "{type='buff';disabled=true;duration=10;anchor='spells';class='MONK';cooldown=90;cdAnchor='cooldowns';}",
		[77606] = "{disabled=true;anchor='damage';disabled=true;duration=8;cooldown=60;cdDisabled=true;cdAnchor='cooldowns';class='DEATHKNIGHT';}",
		[6544] = "{cooldown=45;cdDisabled=true;cdAnchor='cooldowns';class='WARRIOR';}",
		[115203] = "{type='buff';disabled=true;duration=20;anchor='defenses';cooldown=180;cdAnchor='cooldowns';class='MONK';}",
		[51490] = "{cdDisabled=true;class='SHAMAN';cooldown=45;cdAnchor='spells';}",
		[51514] = "{disabled=true;cdDisabled=false;class='SHAMAN';cooldown=45;cdAnchor='spells';}",
		[105593] = "{disabled=true;cdDisabled=false;class='PALADIN';cooldown=30;cdAnchor='cooldowns';}",
		[2139] = "{cooldown=24;cdAnchor='interrupts';class='MAGE';}",
		[172106] = "{duration=6;anchor='buffs';cooldown=180;cdAnchor='cooldowns';class='HUNTER';}",
		[49028] = "{class='DEATHKNIGHT';disabled=true;cdDisabled=true;anchor='damage';duration=8;cooldown=90;cdAnchor='cooldowns';}",
		[108271] = "{type='buff';disabled=true;duration=6;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=90;class='SHAMAN';}",
		[31224] = "{type='buff';disabled=true;class='ROGUE';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=60;duration=5;}",
		[107570] = "{cooldown=30;cdAnchor='cooldowns';class='WARRIOR';}",
		[115284] = "{cooldown=15;cdAnchor='spells';cdDisabled=true;class='WARLOCK';}",
		[19263] = "{class='HUNTER';type='buff';disabled=true;cdDisabled=false;anchor='defenses';duration=5;cooldown=180;cdAnchor='cooldowns';}",
		[98008] = "{type='totem';duration=3;anchor='buffs';cooldown=45;cdAnchor='cooldowns';class='SHAMAN';}",
		[102359] = "{cooldown=30;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[19574] = "{type='buff';disabled=true;class='HUNTER';cdAnchor='cooldowns';cdDisabled=false;anchor='damage';cooldown=60;duration=10;}",
		[102280] = "{cooldown=30;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[119381] = "{cooldown=45;cdDisabled=true;cdAnchor='cooldowns';class='MONK';}",
		[115078] = "{cooldown=15;cdAnchor='spells';class='MONK';}",
		[1719] = "{type='buff';disabled=true;class='WARRIOR';cdAnchor='cooldowns';cdDisabled=false;anchor='damage';cooldown=180;duration=12;}",
		[8122] = "{cdDisabled=true;class='PRIEST';cooldown=90;cdAnchor='spells';}",
		[5277] = "{type='buff';disabled=true;class='ROGUE';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=120;duration=10;}",
		[45438] = "{type='buff';disabled=true;class='MAGE';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=300;duration=10;}",
		[108201] = "{disabled=true;anchor='damage';disabled=true;duration=10;cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='DEATHKNIGHT';}",
		[57994] = "{cooldown=12;cdAnchor='interrupts';class='SHAMAN';}",
		[46924] = "{type='buff';disabled=true;duration=6;anchor='damage';cooldown=60;cdAnchor='cooldowns';class='WARRIOR';}",
		[113724] = "{disabled=true;class='MAGE';duration=10;cooldown=45;cdAnchor='cooldowns';}",
		[48792] = "{type='buff';disabled=true;duration=8;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=180;class='DEATHKNIGHT';}",
		[114039] = "{disabled=true;type='buff';duration=6;anchor='defenses';cdDisabled=true;cooldown=30;cdAnchor='cooldowns';class='PALADIN';}",
		[55233] = "{type='buff';disabled=true;class='DEATHKNIGHT';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=60;duration=10;}",
		[13813] = "{cooldown=15;cdAnchor='cooldowns';class='HUNTER';}",
		[108194] = "{cooldown=30;cdAnchor='interrupts';class='DEATHKNIGHT';}",
		[152151] = "{duration=16;anchor='damage';cdDisabled=true;cooldown=120;cdAnchor='cooldowns';class='ROGUE';}",
		[47585] = "{type='buff';disabled=true;duration=6;anchor='defenses';class='PRIEST';cooldown=120;cdAnchor='cooldowns';}",
		[76577] = "{cdDisabled=false;class='ROGUE';cooldown=180;cdAnchor='cooldowns';}",
		[1850] = "{type='buff';disabled=true;duration=15;anchor='buffs';cooldown=180;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[115770] = "{cdDisabled=true;class='WARLOCK';cooldown=25;cdAnchor='spells';}",
		[116705] = "{cooldown=15;cdAnchor='interrupts';class='MONK';}",
		[3411] = "{cooldown=30;cdDisabled=true;cdAnchor='defenses';class='WARRIOR';}",
		[51690] = "{duration=3;anchor='damage';cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='ROGUE';}",
		[15487] = "{cooldown=45;cdAnchor='interrupts';class='PRIEST';}",
		[8143] = "{type='totem';disabled=true;duration=5;anchor='buffs';repeating=true;cooldown=60;cdAnchor='cooldowns';class='SHAMAN';}",
		[77764] = "{type='buff';disabled=true;duration=12;anchor='buffs';cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[115781] = "{cooldown=24;cdAnchor='interrupts';class='WARLOCK';}",
		[19505] = "{cooldown=15;cdAnchor='spells';cdDisabled=true;class='WARLOCK';}",
		[114028] = "{type='buff';disabled=true;duration=5;cdDisabled=true;cooldown=30;cdAnchor='cooldowns';class='WARRIOR';}",
		[642] = "{type='buff';disabled=true;class='PALADIN';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=300;duration=8;}",
		[48743] = "{duration=15;cdDisabled=true;anchor='defenses';class='DEATHKNIGHT';cooldown=120;cdAnchor='spells';}",
		[47476] = "{cooldown=60;cdAnchor='interrupts';class='DEATHKNIGHT';}",
		[106952] = "{type='buff';duration=20;anchor='damage';cooldown=180;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[112833] = "{cooldown=30;cdAnchor='cooldowns';class='PRIEST';}",
		[6940] = "{type='buff';disabled=true;duration=12;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=120;class='PALADIN';}",
		[408] = "{cdDisabled=true;class='ROGUE';cooldown=20;cdAnchor='spells';}",
		[108291] = "{type='buff';duration=45;anchor='damage';cooldown=360;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[137562] = "{type='buff';disabled=true;duration=6;anchor='defenses';cooldown=120;cdAnchor='cooldowns';class='MONK';}",
		[1856] = "{type='buff';disabled=true;duration=10;anchor='defenses';cooldown=120;cdAnchor='cooldowns';class='ROGUE';}",
		[107574] = "{type='buff';disabled=true;duration=24;anchor='damage';cooldown=180;cdAnchor='cooldowns';class='WARRIOR';}",
		[115750] = "{cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='PALADIN';}",
		[1953] = "{cooldown=15;cdDisabled=true;cdAnchor='cooldowns';class='MAGE';}",
		[871] = "{type='buff';disabled=true;duration=12;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=180;class='WARRIOR';}",
		[18499] = "{type='buff';disabled=true;class='WARRIOR';anchor='spells';duration=6;cooldown=30;cdAnchor='cooldowns';}",
		[114029] = "{cooldown=30;cdDisabled=true;cdAnchor='defenses';class='WARRIOR';}",
		[102060] = "{disabled=false;class='WARRIOR';cooldown=40;cdAnchor='interrupts';}",
		[22842] = "{cooldown=180;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[13750] = "{duration=15;disabled=true;cdDisabled=false;anchor='damage';class='ROGUE';cooldown=180;cdAnchor='cooldowns';}",
		[51052] = "{class='DEATHKNIGHT';disabled=true;cdDisabled=true;anchor='defenses';duration=3;cooldown=120;cdAnchor='cooldowns';}",
		[6552] = "{cooldown=15;cdAnchor='interrupts';class='WARRIOR';}",
		[116849] = "{type='buff';disabled=true;duration=12;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=120;class='MONK';}",
		[106839] = "{cooldown=15;cdAnchor='interrupts';class='DRUID';}",
		[108292] = "{type='buff';duration=45;anchor='damage';cooldown=360;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[1766] = "{cooldown=15;cdAnchor='interrupts';class='ROGUE';}",
		[115176] = "{type='buff';disabled=true;duration=8;anchor='defenses';cooldown=180;cdAnchor='cooldowns';class='MONK';}",
		[114018] = "{duration=15;anchor='buffs';cdDisabled=true;cooldown=300;cdAnchor='cooldowns';class='ROGUE';}",
		[853] = "{disabled=true;cdDisabled=false;class='PALADIN';cooldown=60;cdAnchor='cooldowns';}",
		[6360] = "{cdDisabled=true;class='WARLOCK';cooldown=25;cdAnchor='spells';}",
		[8177] = "{type='totem';disabled=true;duration=15;anchor='buffs';cooldown=25;cdAnchor='cooldowns';class='SHAMAN';}",
		[51713] = "{duration=10;anchor='damage';cooldown=60;cdAnchor='cooldowns';class='ROGUE';}",
		[51533] = "{disabled=true;duration=15;anchor='damage';cooldown=120;cdDisabled=true;cdAnchor='cooldowns';class='SHAMAN';}",
		[74001] = "{type='buff';disabled=true;class='ROGUE';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=120;duration=20;}",
		[64044] = "{disabled=true;cdDisabled=false;class='PRIEST';cooldown=45;cdAnchor='spells';}",
		[108978] = "{cooldown=90;cdAnchor='spells';class='MAGE';}",
		[60192] = "{type='trap';configName='frost';cooldownName='frost';disabled=true;duration=60;anchor='spells';cooldown=15;cdDisabled=true;cdAnchor='cooldowns';class='HUNTER';}",
		[30823] = "{type='buff';disabled=true;duration=15;cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=60;class='SHAMAN';}",
		[1022] = "{type='buff';disabled=true;class='PALADIN';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=300;duration=10;}",
		[49039] = "{type='buff';disabled=true;class='DEATHKNIGHT';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=120;duration=10;}",
		[108293] = "{type='buff';duration=45;anchor='damage';cooldown=360;cdDisabled=true;cdAnchor='cooldowns';class='DRUID';}",
		[108359] = "{type='buff';duration=12;anchor='defenses';cooldown=120;cdAnchor='cooldowns';class='WARLOCK';}",
		[47788] = "{type='buff';disabled=true;class='PRIEST';cdAnchor='cooldowns';cdDisabled=false;anchor='defenses';cooldown=180;duration=10;}",
		[47482] = "{cooldown=30;cdDisabled=true;cdAnchor='spells';class='DEATHKNIGHT';}",
		[5246] = "{cooldown=90;cdDisabled=true;cdAnchor='cooldowns';class='WARRIOR';}",
	}
	Afflicted.db.profile.inside = {
		["pvp"] = false,
		["none"] = false,
	}
	Afflicted.db.profile.spellVersion = 15
	Afflicted.db.profile.showAnchors = false

	Afflicted.modules.Bars:ReloadVisual()
	Afflicted.modules.Icons:ReloadVisual()
	Afflicted:Reload()
	LibStub("AceConfigRegistry-3.0"):NotifyChange("Afflicted")

end